#!/usr/bin/env bash

# Takes stdin and outputs to stdout. Suitable for usage on vim buffers or highlights.
# http://stackoverflow.com/a/16090892/4376

xmllint --format -

# TODO - should not mess up non-ascii values. Eg:
# <attrib>
#   <atype>dir</atype>
#   <value>St.Pölten Hbf</value>
# </attrib>
