#!/bin/bash

# Usage: `judge rspec spec`; runs yay or boom depending on exit status

# Explanation:
# - `$@` means "expand all the args that I was given"
# - `"$@"` makes sure that quoting is preserved - eg, if the command was
#    `judge echo one "two three"` we'll have two args, not three
# - Once the expansion is done, the shell sees a bare command and runs it. If
#   we'd put `echo "$@"` instead, that might expand to `echo rspec spec`, so it
#   would run `echo` and pass in the arguments `rspec` and `spec`

"$@" && yay || boom
