#!/bin/bash
# Convert a file from markdown to html and open in a browser

# cmark is from https://github.com/jgm/cmark
cmark "$1" > /tmp/markdown_output.html;

# If that worked, and we were told to open it
if [ $? -eq 0 ] && [ "$2" = "open" ]; then
  # Open the html in a browser
  open /tmp/markdown_output.html &
fi
