. ~/.zsh/config
. ~/.zsh/aliases
. ~/.zsh/completion

# use .localrc for settings specific to one system
[[ -f ~/.localrc ]] && .  ~/.localrc

# Remember about a years worth of history (AWESOME)
SAVEHIST=10000
HISTSIZE=10000
