# NOTE that this is run after ~/.zshenv, and only for interactive shells
# Put together all these files
. ~/.dotfiles/zsh/paths
. ~/.dotfiles/zsh/misc
. ~/.dotfiles/zsh/colors
. ~/.dotfiles/zsh/history
. ~/.dotfiles/zsh/bindings
. ~/.dotfiles/zsh/mac
. $HOME/.asdf/asdf.sh
. $HOME/.asdf/completions/asdf.bash
. ~/.dotfiles/zsh/prompt # may print warnings unless proper Ruby version is set

# use .zshrc_machine_specific for settings specific to one machine
[[ -f ~/.zshrc_machine_specific ]] && .  ~/.zshrc_machine_specific

. ~/.dotfiles/zsh/env_vars
. ~/.dotfiles/zsh/api_keys
