# Disable terminal flow control (Ctrl+S/Ctrl+Q) to allow Ctrl+S to be used in applications like vim
stty -ixon

# NOTE that this is run after ~/.zshenv, and only for interactive shells
# Put together all these files
. ~/.dotfiles/zsh/paths
. ~/.dotfiles/zsh/misc
. ~/.dotfiles/zsh/colors
. ~/.dotfiles/zsh/history
. ~/.dotfiles/zsh/bindings
. ~/.dotfiles/zsh/mac
# source if exists
[[ -f /opt/homebrew/opt/asdf/libexec/asdf.sh ]] && . /opt/homebrew/opt/asdf/libexec/asdf.sh
[[ -f $HOME/.asdf/asdf.sh ]] && . $HOME/.asdf/asdf.sh
. ~/.dotfiles/zsh/prompt # may print warnings unless proper Ruby version is set

# use .zshrc_machine_specific for settings specific to one machine
[[ -f ~/.zshrc_machine_specific ]] && .  ~/.zshrc_machine_specific

. ~/.dotfiles/zsh/env_vars
# source if exists
[[ -f ~/.dotfiles/zsh/api_keys ]] && . ~/.dotfiles/zsh/api_keys
