# NOTE that this is run after ~/.zshenv, and only for interactive shells
# Put together all these files
. ~/.dotfiles/zsh/paths
. ~/.dotfiles/zsh/misc
. ~/.dotfiles/zsh/colors
. ~/.dotfiles/zsh/history
. ~/.dotfiles/zsh/bindings
. ~/.dotfiles/zsh/prompt
. ~/.dotfiles/zsh/lion
. ~/.dotfiles/zsh/chruby

# use .zshrc_machine_specific for settings specific to one machine
[[ -f ~/.zshrc_machine_specific ]] && .  ~/.zshrc_machine_specific

# So that that shelling out from Vim with `zsh -i` will load .zshrc
# (see `man zsh` and search for ZDOTDIR)
export ZDOTDIR=$HOME

# Add custom scripts folder to the path
export PATH="$HOME/.dotfiles/scripts:$PATH"

# display manfiles in Vim in readonly mode, after throwing out extra backspace
# characters.
# https://zameermanji.com/blog/2012/12/30/using-vim-as-manpager/
export MANPAGER="/bin/sh -c \"col -b | vim -c 'set ft=man ts=8 nomod nolist nonu noma' -\""
