source ~/.bash/aliases
source ~/.bash/completions
source ~/.bash/paths
source ~/.bash/config

if [ -f ~/.bashrc ]; then
  . ~/.bashrc
fi

if [ -f ~/.localrc ]; then
  . ~/.localrc
fi

# Enable chruby
source /usr/local/opt/chruby/share/chruby/chruby.sh

# Enable auto-switching of Rubies specified by .ruby-version files
source /usr/local/opt/chruby/share/chruby/auto.sh
